version: '3.8'
services:
  db:
    image: mysql:latest
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      -"3306:3306"
    volumes:
      - mysqldata:/var/lib/mysql
volumes:
  mysqldata: